language: node_js
node_js:
  - "8"
  - "10"
  - "12"

env:
  - NODE_ENV=development

cache:
  directories:
    - "node_modules"

script:
  - npm run build
  - npm test
  - npx codecov

notifications:
  email: false
